### ISSUE TITLE
something wrong and cannot vist

### ISSUE THREAD

**Issue by KIDxiaoyuan** [noagarcia/context-art-classification#1]
when i try to download the dataset and pre-trained models pre-computed graph embeddings,it tell me 404...
so i try to train it.
firstly i set the dataset_dir by SemArt which download form Art-Description poj.
then when i run the `main.py --mode train --model mtl --dir_dataset Data/SemArt`
there is something wrong with follows.
i don't konw where is wrong ,and have no idea to fix it .

if i want to rung the retrieve_knowledge.py in poj Art-Description , second part "KnowledgeRetrieval" ,am i must run the context_art_classification ,DrQA,faster_rcnn before?

`
 Options 
att: all
batch_size: 128
csvtest: semart_test.csv
csvtrain: semart_train.csv
csvval: semart_val.csv
dir_data: Data
dir_dataset: Data/SemArt
dir_images: Images/
dir_model: Models/
graph_embs: semart-artgraph-node2vec.model
lambda_c: 0.9
lambda_e: 0.1
lr: 0.001
mode: train
model: mtl
model_path: Models/best-kgm-time-model.pth.tar
momentum: 0.9
name: mtl-all
nepochs: 300
no_cuda: False
patience: 30
resume: 
seed: 123
use_gpu: True
vocab_author: author2ind.pckl
vocab_school: school2ind.pckl
vocab_time: time2ind.pckl
vocab_type: type2ind.pckl
workers: 8

Setting up a new session...
Exception in user code:

Traceback (most recent call last):
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/server1/anaconda3/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/server1/anaconda3/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/server1/anaconda3/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/server1/anaconda3/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/server1/anaconda3/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0ea70faf10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server1/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/server1/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=18419): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ea70faf10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server1/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/server1/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/server1/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/server1/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/server1/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/server1/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=18419): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ea70faf10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/server1/PythonCodes/XiaoYuan/code/Art-Description-main/KnowledgeRetrieval/context_art_classification/main.py", line 34, in <module>
    run_train(args_dict)
  File "/home/server1/PythonCodes/XiaoYuan/code/Art-Description-main/KnowledgeRetrieval/context_art_classification/train.py", line 388, in run_train
    train_multitask_classifier(args_dict)
  File "/home/server1/PythonCodes/XiaoYuan/code/Art-Description-main/KnowledgeRetrieval/context_art_classification/train.py", line 292, in train_multitask_classifier
    type2idx, school2idx, time2idx, author2idx = load_att_class(args_dict)
  File "/home/server1/PythonCodes/XiaoYuan/code/Art-Description-main/KnowledgeRetrieval/context_art_classification/attributes.py", line 22, in load_att_class
    author2idx = utils.load_obj(author_file)
  File "/home/server1/PythonCodes/XiaoYuan/code/Art-Description-main/KnowledgeRetrieval/context_art_classification/utils.py", line 15, in load_obj
    obj = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 3: ordinal not in range(128)
`

**Comment by achiatti** [comment]
I encountered the same issue as you because I was trying to run this code on Google Colab with Python3. The connection issue seems to be related to the visdom server used for plotting. In my case Colab does not interface with visdom so commenting out the lines of code (in utils.py and train.py) that invoke/import the visdom methods was the easiest fix. In your specific case it may have to do with other configuration issues of your visdom server. 

The second part of the error (UnicodeDecodeError) in my case was because, as specified in the docs, this code was developed in python 2.7 so to run it with python3 some minor adjustments need to be made to decode the python2 pickle files correctly.
Changing line 15 in utils.py to
```obj = pickle.load(f,encoding="latin1")```
did it for me. Hope this helps!
